import 'notifier/qr_codetwo_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';class QrCodetwoScreen extends ConsumerStatefulWidget {const QrCodetwoScreen({Key? key}) : super(key: key);

@override QrCodetwoScreenState createState() =>  QrCodetwoScreenState();

 }
class QrCodetwoScreenState extends ConsumerState<QrCodetwoScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: GestureDetector(onTap: () {onTapView(context);}, child: Container(margin: EdgeInsets.all(24.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 7.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisSize: MainAxisSize.min, children: [Container(height: 88.v, width: 78.h, decoration: AppDecoration.fillOrange.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: CustomImageView(imagePath: ImageConstant.imgImage81, height: 88.v, width: 78.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 12.h, right: 8.h, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 16.v, width: 89.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(height: 16.v, width: 89.h, decoration: BoxDecoration(color: appTheme.orange100, borderRadius: BorderRadius.circular(4.h)))), Align(alignment: Alignment.topCenter, child: Text("lbl_intermediate".tr.toUpperCase(), style: CustomTextStyles.labelMediumOrange800))])), SizedBox(height: 11.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_suman_nithyanand".tr, style: CustomTextStyles.titleSmallExtraBold), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconCommuGray600, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_9856784536".tr, style: CustomTextStyles.bodySmall10))]), SizedBox(height: 4.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconInterGray600, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_25_12_2023".tr, style: CustomTextStyles.bodySmall10))])]), CustomImageView(imagePath: ImageConstant.imgHugeIconArrow, height: 24.v, width: 23.h, margin: EdgeInsets.only(top: 4.v, bottom: 29.v))])]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_manage_visits2".tr), styleType: Style.bgFill_2); } 
/// Navigates to the mainHomescreenScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.mainHomescreenScreen, ); } 
/// Navigates to the k87Screen when the action is triggered.
onTapView(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k87Screen, ); } 
 }
