import '../thirtytwo_screen/widgets/userprofilelist_item_widget.dart';import 'models/userprofilelist_item_model.dart';import 'notifier/thirtytwo_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/core/utils/validation_functions.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_icon_button.dart';import 'package:tissue_culture/widgets/custom_text_form_field.dart';class ThirtytwoScreen extends ConsumerStatefulWidget {const ThirtytwoScreen({Key? key}) : super(key: key);

@override ThirtytwoScreenState createState() =>  ThirtytwoScreenState();

 }

// ignore_for_file: must_be_immutable
class ThirtytwoScreenState extends ConsumerState<ThirtytwoScreen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Column(children: [_buildFillStack(context), SizedBox(height: 12.v), _buildUserProfileList(context), SizedBox(height: 22.v), _buildFrameRow(context), SizedBox(height: 16.v), _buildParticipantsColumn(context), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 24.h, right: 28.h), child: _buildPlantVarietyRow(context, plantvariety: "lbl_disease".tr)), SizedBox(height: 16.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(thirtytwoNotifier).nameController, hintText: "msg_name_of_disease_detail".tr, hintStyle: theme.textTheme.bodySmall!, textInputAction: TextInputAction.done, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 11.v));})), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 24.h, right: 28.h), child: _buildPlantVarietyRow(context, plantvariety: "lbl_plant_variety".tr)), SizedBox(height: 14.v), _buildBgStack(context), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_features_of_plant".tr, style: CustomTextStyles.titleMediumPrimaryContainer))), SizedBox(height: 62.v), Padding(padding: EdgeInsets.only(right: 28.h), child: _buildIcStack(context)), SizedBox(height: 18.v), _buildBgStack1(context), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_yield_parameters".tr, style: CustomTextStyles.titleMediumPrimaryContainer))), SizedBox(height: 206.v), Padding(padding: EdgeInsets.only(right: 28.h), child: _buildIcStack(context)), SizedBox(height: 18.v), _buildBgStack2(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_plant_detail".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildFillStack(BuildContext context) { return Container(height: 230.v, width: double.maxFinite, decoration: AppDecoration.fillBlack, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgRectangle88, height: 230.v, width: 360.h, alignment: Alignment.center), Padding(padding: EdgeInsets.only(top: 16.v, right: 23.h), child: CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.topRight, child: CustomImageView(imagePath: ImageConstant.imgFill)))])); } 
/// Section Widget
Widget _buildUserProfileList(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.all(8.h), decoration: AppDecoration.fillPrimaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Consumer(builder: (context, ref, _) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: ref.watch(thirtytwoNotifier).thirtytwoModelObj?.userprofilelistItemList.length ?? 0, itemBuilder: (context, index) {UserprofilelistItemModel model = ref.watch(thirtytwoNotifier).thirtytwoModelObj?.userprofilelistItemList[index] ?? UserprofilelistItemModel(); return UserprofilelistItemWidget(model);});})); } 
/// Section Widget
Widget _buildFrameRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 24.h, right: 28.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_plant_details".tr, style: CustomTextStyles.titleMediumPrimaryContainer), Padding(padding: EdgeInsets.only(top: 3.v), child: CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgFill)))])); } 
/// Section Widget
Widget _buildParticipantsColumn(BuildContext context) { return Container(width: 312.h, margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 9.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), SizedBox(width: 152.h, child: Text("msg_plant_code_expected".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall!.copyWith(height: 1.33)))])); } 
/// Section Widget
Widget _buildBgStack(BuildContext context) { return SizedBox(height: 56.v, width: 312.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: Container(height: 56.v, width: 312.h, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1), borderRadius: BorderRadius.circular(12.h)))), Align(alignment: Alignment.centerLeft, child: Container(width: 104.h, margin: EdgeInsets.only(left: 12.h), child: Text("msg_plant_species_name_plant".tr, maxLines: null, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall!.copyWith(height: 1.33))))])); } 
/// Section Widget
Widget _buildBgStack1(BuildContext context) { return SizedBox(height: 88.v, width: 312.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: Container(height: 88.v, width: 312.h, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1), borderRadius: BorderRadius.circular(12.h)))), Align(alignment: Alignment.centerLeft, child: Container(width: 128.h, margin: EdgeInsets.only(left: 12.h), child: Text("msg_plant_height_stature_number".tr, maxLines: null, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall!.copyWith(height: 1.33))))])); } 
/// Section Widget
Widget _buildBgStack2(BuildContext context) { return SizedBox(height: 56.v, width: 312.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: Container(height: 56.v, width: 312.h, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1), borderRadius: BorderRadius.circular(12.h)))), Align(alignment: Alignment.centerLeft, child: Container(width: 107.h, margin: EdgeInsets.only(left: 12.h), child: Text("msg_weight_kg_number".tr, maxLines: null, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall!.copyWith(height: 1.33))))])); } 
/// Common widget
Widget _buildPlantVarietyRow(BuildContext context, {required String plantvariety, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(plantvariety, style: CustomTextStyles.titleMediumPrimaryContainer.copyWith(color: theme.colorScheme.primaryContainer.withOpacity(1))), Container(height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 3.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgFill, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgEdit, height: 10.adaptSize, width: 10.adaptSize, alignment: Alignment.center)]))]); } 
/// Common widget
Widget _buildIcStack(BuildContext context) { return SizedBox(height: 20.adaptSize, width: 20.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgFill, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgEdit, height: 10.adaptSize, width: 10.adaptSize, alignment: Alignment.center)])); } 
/// Navigates to the thirtyoneTabContainerScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.thirtyoneTabContainerScreen, ); } 
 }
