import 'notifier/k148_notifier.dart';import 'package:flutter/material.dart';import 'package:qr_flutter/qr_flutter.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';class K148Screen extends ConsumerStatefulWidget {const K148Screen({Key? key}) : super(key: key);

@override K148ScreenState createState() =>  K148ScreenState();

 }
class K148ScreenState extends ConsumerState<K148Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 56.v), child: Column(children: [SizedBox(height: 46.v), Container(width: 247.h, margin: EdgeInsets.symmetric(horizontal: 32.h), child: Text("msg_please_verify_the".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray600.copyWith(height: 1.43))), SizedBox(height: 14.v), _buildExampleOfQRCode(context), Spacer(), CustomElevatedButton(text: "lbl_scan_storage_qr".tr, onPressed: () {onTapScanStorageQR(context);}), SizedBox(height: 13.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 12.v), GestureDetector(onTap: () {onTapTxtEnterTheDetail(context);}, child: Text("msg_enter_the_detail".tr, style: CustomTextStyles.titleSmallPrimary_1))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "msg_allocate_storage2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildExampleOfQRCode(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_07".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_da".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080808".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_2".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_m".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_1".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 13.v, bottom: 47.v), child: Text("lbl_bm1".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)), Padding(padding: EdgeInsets.only(left: 20.h), child: QrImageView(data: 'https://www.google.com', size: 93.adaptSize)), Padding(padding: EdgeInsets.only(left: 11.h, top: 13.v, bottom: 15.v), child: Column(children: [SizedBox(width: 116.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_888".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080622".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold))])]))])), SizedBox(height: 5.v)])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 8.v, bottom: 9.v), child: SizedBox(width: 140.h, child: Divider())), Text("lbl_or".tr, style: CustomTextStyles.bodySmallGray90002), Padding(padding: EdgeInsets.only(top: 8.v, bottom: 9.v), child: SizedBox(width: 140.h, child: Divider()))]); } 
/// Navigates to the k146Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k146Screen, ); } 
/// Navigates to the k150Screen when the action is triggered.
onTapScanStorageQR(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k150Screen, ); } 
/// Navigates to the k149Screen when the action is triggered.
onTapTxtEnterTheDetail(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k149Screen, ); } 
 }
