import 'notifier/twelve2_notifier.dart';import 'package:flutter/material.dart';import 'package:qr_flutter/qr_flutter.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';class Twelve2Screen extends ConsumerStatefulWidget {const Twelve2Screen({Key? key}) : super(key: key);

@override Twelve2ScreenState createState() =>  Twelve2ScreenState();

 }
class Twelve2ScreenState extends ConsumerState<Twelve2Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 22.h, top: 104.v, right: 22.h), child: Column(children: [_buildHarding(context), SizedBox(height: 40.v), Container(margin: EdgeInsets.symmetric(horizontal: 84.h), padding: EdgeInsets.symmetric(horizontal: 58.h, vertical: 11.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPrint, height: 32.adaptSize, width: 32.adaptSize), SizedBox(height: 2.v), Text("lbl_print".tr, style: CustomTextStyles.bodyMediumBlack900)])), SizedBox(height: 5.v)])), bottomNavigationBar: _buildGenerateQRCode(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_hardening_label".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildHarding(BuildContext context) { return Container(margin: EdgeInsets.only(right: 4.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_07".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_da".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080808".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_2".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_m".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_1".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.symmetric(horizontal: 27.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [QrImageView(data: 'https://www.google.com', size: 93.adaptSize), Padding(padding: EdgeInsets.only(left: 24.h, top: 13.v, bottom: 15.v), child: Column(children: [SizedBox(width: 116.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_888".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080622".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold))])]))])), SizedBox(height: 5.v)])); } 
/// Section Widget
Widget _buildGenerateQRCode(BuildContext context) { return CustomElevatedButton(text: "msg_generate_qr_code".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapGenerateQRCode(context);}); } 
/// Navigates to the eleven2Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.eleven2Screen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapGenerateQRCode(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
 }
