import 'notifier/k53_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/presentation/defaultmap_page/defaultmap_page.dart';import 'package:tissue_culture/presentation/filed_homescreen_container_page/filed_homescreen_container_page.dart';import 'package:tissue_culture/presentation/k120_page/k120_page.dart';import 'package:tissue_culture/presentation/k45_page/k45_page.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_bottom_bar.dart';import 'package:tissue_culture/widgets/custom_search_view.dart';class K53Screen extends ConsumerStatefulWidget {const K53Screen({Key? key}) : super(key: key);

@override K53ScreenState createState() =>  K53ScreenState();

 }

// ignore_for_file: must_be_immutable
class K53ScreenState extends ConsumerState<K53Screen> {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Consumer(builder: (context, ref, _) {return CustomSearchView(controller: ref.watch(k53Notifier).searchController, hintText: "lbl_search".tr);}), SizedBox(height: 24.v), _buildSearchView(context), Spacer(), SizedBox(height: 8.v), Container(height: 48.adaptSize, width: 48.adaptSize, decoration: AppDecoration.outlineBlack9001, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgBg, height: 48.adaptSize, width: 48.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgPlus, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center)]))])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_manage_visits2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildSearchView(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 7.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [Container(padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 35.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Text("lbl_no_image".tr.toUpperCase(), style: CustomTextStyles.labelMediumPrimaryContainer)), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 16.v, width: 67.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(height: 16.v, width: 67.h, decoration: BoxDecoration(color: appTheme.blue100, borderRadius: BorderRadius.circular(4.h)))), Align(alignment: Alignment.topCenter, child: Text("lbl_first_visit".tr.toUpperCase(), style: CustomTextStyles.labelMediumOnError))])), SizedBox(height: 11.v), SizedBox(width: 197.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_johny_mathew".tr, style: CustomTextStyles.titleSmallExtraBold), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconCommuGray600, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_8976564534".tr, style: CustomTextStyles.bodySmall10))]), SizedBox(height: 4.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconInterGray600, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_02_01_2024".tr, style: CustomTextStyles.bodySmall10))])]), CustomImageView(imagePath: ImageConstant.imgHugeIconArrow, height: 24.v, width: 23.h, margin: EdgeInsets.only(top: 4.v, bottom: 29.v))]))]))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.filedHomescreenContainerPage; case BottomBarEnum.Map: return AppRoutes.defaultmapPage; case BottomBarEnum.Visits: return AppRoutes.k45Page; case BottomBarEnum.Report: return AppRoutes.k120Page; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.filedHomescreenContainerPage: return FiledHomescreenContainerPage(); case AppRoutes.defaultmapPage: return DefaultmapPage(); case AppRoutes.k45Page: return K45Page(); case AppRoutes.k120Page: return K120Page(); default: return DefaultWidget();} } 
/// Navigates to the mainHomescreenScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.mainHomescreenScreen, ); } 
 }
