import 'notifier/k43_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/widgets/custom_icon_button.dart';import 'package:tissue_culture/widgets/custom_text_form_field.dart';import 'package:tissue_culture/presentation/ten_bottomsheet/ten_bottomsheet.dart';class K43Screen extends ConsumerStatefulWidget {const K43Screen({Key? key}) : super(key: key);

@override K43ScreenState createState() =>  K43ScreenState();

 }
class K43ScreenState extends ConsumerState<K43Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_detail_summary".tr, style: CustomTextStyles.titleMediumGray900))), SizedBox(height: 22.v), _buildMap(context), SizedBox(height: 18.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildFarmerDetails(context, farmerDetailsText: "lbl_location".tr)), SizedBox(height: 24.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(k43Notifier).locationController, hintText: "msg_kerala_phhp_g322".tr, hintStyle: theme.textTheme.bodySmall!, textInputAction: TextInputAction.done, maxLines: 3, contentPadding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 15.v));})), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildFarmerDetails(context, farmerDetailsText: "lbl_farmer_details".tr)), SizedBox(height: 24.v), _buildBackground(context), CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), onPressed: () {onTapSave(context);}), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_first_visit2".tr, style: CustomTextStyles.titleMediumPrimaryContainer))), SizedBox(height: 99.v), _buildFrame(context), SizedBox(height: 142.v), Container(decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.outlineBlack900.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 4.v, width: 40.h, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 16.v), CustomImageView(imagePath: ImageConstant.imgClose, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerLeft), SizedBox(height: 40.v), CustomImageView(imagePath: ImageConstant.imgGroupPrimary, height: 104.adaptSize, width: 104.adaptSize), SizedBox(height: 39.v), Text("lbl_congrats".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), SizedBox(height: 12.v), Text("msg_new_farmer_registration".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallGray600), SizedBox(height: 12.v)])))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "msg_farmer_registration".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildMap(BuildContext context) { return SizedBox(height: 128.v, width: 312.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgScreenShot20200518128x312, height: 128.v, width: 312.h, radius: BorderRadius.circular(12.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 20.v, width: 16.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 45.v, right: 138.h))])); } 
/// Section Widget
Widget _buildBackground(BuildContext context) { return SizedBox(height: 176.v, width: 312.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.center, child: Container(height: 176.v, width: 312.h, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1), borderRadius: BorderRadius.circular(12.h)))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 19.h, top: 14.v, right: 72.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_lalit_meshram2".tr, style: theme.textTheme.bodySmall), SizedBox(height: 6.v), Text("msg_kerala_phhp_g323".tr, style: theme.textTheme.bodySmall), SizedBox(height: 5.v), Text("msg_near_paloti_factory2".tr, style: theme.textTheme.bodySmall), SizedBox(height: 5.v), Text("lbl_village_no_0067".tr, style: theme.textTheme.bodySmall), SizedBox(height: 5.v), Text("msg_survey_no_123456".tr, style: theme.textTheme.bodySmall), SizedBox(height: 3.v), Text("lbl_91_8765674534".tr, style: theme.textTheme.bodySmall)])))])); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 16.h), decoration: AppDecoration.fillOnErrorContainer, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 14.v), child: Text("msg_select_the_first".tr, style: theme.textTheme.bodyMedium)), CustomImageView(imagePath: ImageConstant.imgHugeIconInterBlueGray900041x20, height: 1.v, width: 20.h, margin: EdgeInsets.only(top: 14.v))])); } 
/// Common widget
Widget _buildFarmerDetails(BuildContext context, {required String farmerDetailsText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(farmerDetailsText, style: CustomTextStyles.titleMediumPrimaryContainer.copyWith(color: theme.colorScheme.primaryContainer.withOpacity(1))), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgFill))]); } 
/// Navigates to the k42Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k42Screen, ); } 

/// Shows a modal bottom sheet with [TenBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapSave(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>TenBottomsheet(),isScrollControlled: true); } 
 }
