import 'notifier/k152_notifier.dart';import 'package:flutter/material.dart';import 'package:qr_flutter/qr_flutter.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/presentation/k153_bottomsheet/k153_bottomsheet.dart';class K152Screen extends ConsumerStatefulWidget {const K152Screen({Key? key}) : super(key: key);

@override K152ScreenState createState() =>  K152ScreenState();

 }
class K152ScreenState extends ConsumerState<K152Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 22.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_label_details".tr, style: CustomTextStyles.titleMediumGray900Medium))), SizedBox(height: 16.v), _buildQrCode(context), SizedBox(height: 30.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_storage_details".tr, style: CustomTextStyles.titleMediumGray900Medium))), SizedBox(height: 14.v), _buildParticipants4(context), SizedBox(height: 127.v), CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), onPressed: () {onTapSave(context);}), SizedBox(height: 13.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 12.v), GestureDetector(onTap: () {onTapTxtMakeChanges(context);}, child: Text("lbl_make_changes".tr, style: CustomTextStyles.titleSmallPrimary_1)), SizedBox(height: 77.v), Container(decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.outlineBlack900.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 4.v, width: 40.h, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 16.v), CustomImageView(imagePath: ImageConstant.imgClose, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerLeft), SizedBox(height: 50.v), CustomImageView(imagePath: ImageConstant.imgGroupPrimary, height: 104.adaptSize, width: 104.adaptSize), SizedBox(height: 24.v), Container(width: 298.h, margin: EdgeInsets.symmetric(horizontal: 7.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_label_number".tr, style: CustomTextStyles.titleSmallff787979), TextSpan(text: "msg_07_01_da_080808".tr, style: CustomTextStyles.titleSmallff787979ExtraBold.copyWith(height: 1.71))]), textAlign: TextAlign.center)), SizedBox(height: 123.v), CustomElevatedButton(text: "lbl_back_to_home".tr), SizedBox(height: 8.v)])))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "msg_allocate_storage2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildQrCode(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_07".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_da".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080808".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_2".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_m".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_1".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 13.v, bottom: 47.v), child: Text("lbl_bm1".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)), Padding(padding: EdgeInsets.only(left: 20.h), child: QrImageView(data: 'https://www.google.com', size: 93.adaptSize)), Padding(padding: EdgeInsets.only(left: 11.h, top: 13.v, bottom: 15.v), child: Column(children: [SizedBox(width: 116.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_888".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080622".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold))])]))])), SizedBox(height: 5.v)])); } 
/// Section Widget
Widget _buildParticipants4(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 9.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(right: 2.h), child: _buildParticipants(context, rackNumber: "msg_growth_room_number".tr, participantCount: "lbl_01".tr)), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(right: 2.h), child: _buildParticipants(context, rackNumber: "lbl_rack_number".tr, participantCount: "lbl_1".tr)), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(right: 2.h), child: _buildParticipants(context, rackNumber: "lbl_column_number".tr, participantCount: "lbl_1".tr))])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 8.v, bottom: 9.v), child: SizedBox(width: 140.h, child: Divider())), Padding(padding: EdgeInsets.only(left: 9.h), child: Text("lbl_or".tr, style: CustomTextStyles.bodySmallGray90002)), Padding(padding: EdgeInsets.only(top: 8.v, bottom: 9.v), child: SizedBox(width: 149.h, child: Divider(indent: 9.h)))])); } 
/// Common widget
Widget _buildParticipants(BuildContext context, {required String rackNumber, required String participantCount, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(rackNumber, style: CustomTextStyles.bodyMediumGray600.copyWith(color: appTheme.gray600)), Text(participantCount, style: CustomTextStyles.titleSmallExtraBold.copyWith(color: theme.colorScheme.primaryContainer.withOpacity(1)))]); } 
/// Navigates to the k150Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k150Screen, ); } 

/// Shows a modal bottom sheet with [K153Bottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapSave(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>K153Bottomsheet(),isScrollControlled: true); } 
/// Navigates to the k149Screen when the action is triggered.
onTapTxtMakeChanges(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k149Screen, ); } 
 }
