import 'notifier/k174_notifier.dart';import 'package:flutter/material.dart';import 'package:qr_flutter/qr_flutter.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';class K174Screen extends ConsumerStatefulWidget {const K174Screen({Key? key}) : super(key: key);

@override K174ScreenState createState() =>  K174ScreenState();

 }
class K174ScreenState extends ConsumerState<K174Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 18.h, top: 103.v, right: 18.h), child: Column(children: [SizedBox(width: 222.h, child: Text("msg_please_verify_the2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray600.copyWith(height: 1.43))), SizedBox(height: 17.v), _buildExampleOfQRCode(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinue(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_quality_check".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildExampleOfQRCode(BuildContext context) { return Container(margin: EdgeInsets.only(left: 12.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_07".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_da".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080808".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_2".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_m".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_1".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 13.v, bottom: 47.v), child: Text("lbl_bm1".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)), Padding(padding: EdgeInsets.only(left: 20.h), child: QrImageView(data: 'https://www.google.com', size: 93.adaptSize)), Padding(padding: EdgeInsets.only(left: 11.h, top: 13.v, bottom: 15.v), child: Column(children: [SizedBox(width: 116.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_888".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080622".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold))])]))])), SizedBox(height: 5.v)])); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapContinue(context);}); } 
/// Navigates to the k172Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k172Screen, ); } 
/// Navigates to the k175Screen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k175Screen, ); } 
 }
