import 'notifier/k50_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_six.dart';import 'package:tissue_culture/widgets/app_bar/appbar_trailing_image.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';class K50Screen extends ConsumerStatefulWidget {const K50Screen({Key? key}) : super(key: key);

@override K50ScreenState createState() =>  K50ScreenState();

 }
class K50ScreenState extends ConsumerState<K50Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(margin: EdgeInsets.all(24.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 7.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisSize: MainAxisSize.min, children: [Container(height: 88.v, width: 78.h, decoration: AppDecoration.fillOrange.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: CustomImageView(imagePath: ImageConstant.imgImage8188x78, height: 88.v, width: 78.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 12.h, right: 8.h, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 16.v, width: 67.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(height: 16.v, width: 67.h, decoration: BoxDecoration(color: appTheme.blue100, borderRadius: BorderRadius.circular(4.h)))), Align(alignment: Alignment.topCenter, child: Text("lbl_first_visit".tr.toUpperCase(), style: CustomTextStyles.labelMediumOnError))])), SizedBox(height: 11.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_k_v_deyal".tr, style: CustomTextStyles.titleSmallExtraBold), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconCommuGray600, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_9876567893".tr, style: CustomTextStyles.bodySmall10))]), SizedBox(height: 4.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconInterGray600, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_12_12_2023".tr, style: CustomTextStyles.bodySmall10))])]), CustomImageView(imagePath: ImageConstant.imgHugeIconArrow, height: 24.v, width: 23.h, margin: EdgeInsets.only(top: 4.v, bottom: 29.v))])]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), title: AppbarSubtitleSix(text: "lbl_k_v".tr, margin: EdgeInsets.only(left: 28.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgClose, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgFill_3); } 
/// Navigates to the k48Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k48Screen, ); } 
 }
