import 'models/thirtyone_tab_container_model.dart';import 'notifier/thirtyone_tab_container_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/presentation/thirty_page/thirty_page.dart';import 'package:tissue_culture/presentation/thirtyone_page/thirtyone_page.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_drop_down.dart';class ThirtyoneTabContainerScreen extends ConsumerStatefulWidget {const ThirtyoneTabContainerScreen({Key? key}) : super(key: key);

@override ThirtyoneTabContainerScreenState createState() =>  ThirtyoneTabContainerScreenState();

 }

// ignore_for_file: must_be_immutable
class ThirtyoneTabContainerScreenState extends ConsumerState<ThirtyoneTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 22.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 23.h), child: Text("lbl_visit_details".tr, style: CustomTextStyles.titleMediumGray900Medium))), SizedBox(height: 16.v), _buildDateRow(context), SizedBox(height: 16.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_type".tr, items: ref.watch(thirtyoneTabContainerNotifier).thirtyoneTabContainerModelObj?.dropdownItemList ?? [], onChanged: (value) {ref.watch(thirtyoneTabContainerNotifier).selectedDropDownValue = value;});})), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_detail_summary".tr, style: CustomTextStyles.titleMediumGray900Medium))), SizedBox(height: 14.v), _buildTabview(context), SizedBox(height: 420.v, child: TabBarView(controller: tabviewController, children: [ThirtyPage(), ThirtyonePage()]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_first_visit2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildDateRow(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("msg_select_the_next".tr, style: theme.textTheme.bodyMedium)), CustomImageView(imagePath: ImageConstant.imgGroup1000001977, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v))])); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 32.v, width: 312.h, decoration: BoxDecoration(color: appTheme.gray600.withOpacity(0.16), borderRadius: BorderRadius.circular(12.h)), child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.onErrorContainer.withOpacity(1), labelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Avenir', fontWeight: FontWeight.w500), unselectedLabelColor: appTheme.gray600, unselectedLabelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Avenir', fontWeight: FontWeight.w500), indicator: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.horizontal(right: Radius.circular(12.h))), tabs: [Tab(child: Text("lbl_field_details".tr)), Tab(child: Text("lbl_plant_details".tr))])); } 
/// Navigates to the twentysevenScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.twentysevenScreen, ); } 
 }
