import 'notifier/k39_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';class K39Screen extends ConsumerStatefulWidget {const K39Screen({Key? key}) : super(key: key);

@override K39ScreenState createState() =>  K39ScreenState();

 }
class K39ScreenState extends ConsumerState<K39Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 24.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 24.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgGroup1000001989, height: 48.adaptSize, width: 48.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h, top: 12.v, bottom: 10.v), child: Text("msg_select_your_own".tr, style: CustomTextStyles.bodyLargePrimaryContainer))])), SizedBox(height: 26.v), Divider(color: appTheme.gray600), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_downloaded_maps".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 20.v), _buildLeadingIconFrame(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_offline_maps".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildLeadingIconFrame(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgCheckmarkPrimary, height: 36.adaptSize, width: 36.adaptSize, margin: EdgeInsets.only(bottom: 4.v)), Padding(padding: EdgeInsets.only(left: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_map1".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 1.v), Text("lbl_downloading".tr, style: CustomTextStyles.labelLargeGray600)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgHugeIconInterGray900, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 7.v, bottom: 10.v))]))); } 
/// Navigates to the k38Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k38Screen, ); } 
 }
