import 'notifier/k58_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';class K58Screen extends ConsumerStatefulWidget {const K58Screen({Key? key}) : super(key: key);

@override K58ScreenState createState() =>  K58ScreenState();

 }
class K58ScreenState extends ConsumerState<K58Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 13.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildProgressBar(context), SizedBox(height: 23.v), Text("msg_upload_the_image".tr, style: CustomTextStyles.titleMediumGray900Medium), SizedBox(height: 22.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 22.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 20.v), CustomElevatedButton(text: "msg_open_camera_take".tr, leftIcon: Container(margin: EdgeInsets.only(right: 13.h), child: CustomImageView(imagePath: ImageConstant.imgCamera, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL24, buttonTextStyle: CustomTextStyles.labelLargeOnErrorContainer, onPressed: () {onTapOpenCameraTakePhoto(context);}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_first_visit2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildProgressBar(BuildContext context) { return Row(children: [Container(height: 4.v, width: 269.h, margin: EdgeInsets.symmetric(vertical: 7.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 269.h, child: Divider(color: appTheme.gray60002.withOpacity(0.12)))), Align(alignment: Alignment.center, child: SizedBox(width: 90.h, child: Divider(color: theme.colorScheme.primary)))])), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_2_of_3".tr, style: CustomTextStyles.bodySmallBluegray900))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 125.h, vertical: 56.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgUser, height: 20.adaptSize, width: 20.adaptSize), SizedBox(height: 6.v), Text("lbl_select_file".tr, style: CustomTextStyles.labelLargeGray50001)])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 11.v, bottom: 12.v), child: SizedBox(width: 138.h, child: Divider())), Text("lbl_or".tr, style: CustomTextStyles.bodyLargeGray90002), Padding(padding: EdgeInsets.only(top: 11.v, bottom: 12.v), child: SizedBox(width: 138.h, child: Divider()))]); } 
/// Navigates to the k54Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k54Screen, ); } 
/// Navigates to the k59Screen when the action is triggered.
onTapOpenCameraTakePhoto(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k59Screen, ); } 
 }
