import 'models/k55_model.dart';import 'notifier/k55_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/core/utils/validation_functions.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_checkbox_button.dart';import 'package:tissue_culture/widgets/custom_drop_down.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/widgets/custom_text_form_field.dart';import 'package:tissue_culture/presentation/k57_dialog/k57_dialog.dart';class K55Screen extends ConsumerStatefulWidget {const K55Screen({Key? key}) : super(key: key);

@override K55ScreenState createState() =>  K55ScreenState();

 }

// ignore_for_file: must_be_immutable
class K55ScreenState extends ConsumerState<K55Screen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 13.v), child: Column(children: [_buildThirteen(context), SizedBox(height: 23.v), SizedBox(height: 592.v, width: 312.h, child: Stack(alignment: Alignment.center, children: [_buildContinueButton(context), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_enter_the_field".tr, style: CustomTextStyles.titleMediumGray900Medium), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_field".tr, items: ref.watch(k55Notifier).k55ModelObj?.dropdownItemList ?? [], onChanged: (value) {ref.watch(k55Notifier).selectedDropDownValue = value;});}), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_soil".tr, items: ref.watch(k55Notifier).k55ModelObj?.dropdownItemList1 ?? [], onChanged: (value) {ref.watch(k55Notifier).selectedDropDownValue1 = value;});}), SizedBox(height: 16.v), _buildDateRow(context), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_watering".tr, items: ref.watch(k55Notifier).k55ModelObj?.dropdownItemList2 ?? [], onChanged: (value) {ref.watch(k55Notifier).selectedDropDownValue2 = value;});}), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_field2".tr, items: ref.watch(k55Notifier).k55ModelObj?.dropdownItemList3 ?? [], onChanged: (value) {ref.watch(k55Notifier).selectedDropDownValue3 = value;});}), SizedBox(height: 16.v), _buildTitleEditText(context), SizedBox(height: 24.v), _buildPestHistoryCheckBox(context), SizedBox(height: 22.v), _buildNameEditText(context), SizedBox(height: 16.v), _buildTitleEditText1(context)]))])), SizedBox(height: 5.v)]))))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_first_visit2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildThirteen(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 8.v, bottom: 6.v), child: Container(height: 4.v, width: 269.h, decoration: BoxDecoration(color: appTheme.gray60002.withOpacity(0.12), borderRadius: BorderRadius.circular(2.h)), child: ClipRRect(borderRadius: BorderRadius.circular(2.h), child: LinearProgressIndicator(value: 0.33, backgroundColor: appTheme.gray60002.withOpacity(0.12), valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary)))))), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_1_of_3".tr, style: CustomTextStyles.bodySmallBluegray900))]); } 
/// Section Widget
Widget _buildContinueButton(BuildContext context) { return CustomElevatedButton(width: 312.h, text: "lbl_continue".tr, margin: EdgeInsets.only(bottom: 4.v), onPressed: () {onTapContinueButton(context);}, alignment: Alignment.bottomCenter); } 
/// Section Widget
Widget _buildDateRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_select_date_of_planting".tr, style: theme.textTheme.bodyMedium), CustomImageView(imagePath: ImageConstant.imgGroup1000001977, height: 20.adaptSize, width: 20.adaptSize, onTap: () {onTapImgHugeIconTimeAnd(context);})])); } 
/// Section Widget
Widget _buildTitleEditText(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(k55Notifier).titleEditTextController, hintText: "msg_enter_no_of_plants".tr);}); } 
/// Section Widget
Widget _buildPestHistoryCheckBox(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomCheckboxButton(width: 312.h, text: "lbl_pest_history".tr, value: ref.watch(k55Notifier).pestHistoryCheckBox, textStyle: CustomTextStyles.titleMediumBlack900, isRightCheck: true, onChange: (value) {ref.read(k55Notifier.notifier).changeCheckBox1(value);});}); } 
/// Section Widget
Widget _buildNameEditText(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(k55Notifier).nameEditTextController, hintText: "msg_enter_name_of_pest".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}); } 
/// Section Widget
Widget _buildTitleEditText1(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(k55Notifier).titleEditTextController1, hintText: "msg_enter_details_of".tr, textInputAction: TextInputAction.done);}); } 
/// Navigates to the k48Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k48Screen, ); } 
/// Navigates to the k58Screen when the action is triggered.
onTapContinueButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k58Screen, ); } 

/// Displays a dialog with the [K57Dialog] content.
onTapImgHugeIconTimeAnd(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: K57Dialog(),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
