import 'notifier/eleven_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/widgets/custom_icon_button.dart';class ElevenScreen extends ConsumerStatefulWidget {const ElevenScreen({Key? key}) : super(key: key);

@override ElevenScreenState createState() =>  ElevenScreenState();

 }
class ElevenScreenState extends ConsumerState<ElevenScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 13.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [_buildThirtyThree(context), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Text("msg_add_plant_details".tr, style: CustomTextStyles.titleMediumGray900Medium)), SizedBox(height: 110.v), CustomImageView(imagePath: ImageConstant.imgCurrencyCrushOnline, height: 133.v, width: 155.h), SizedBox(height: 22.v), Container(width: 258.h, margin: EdgeInsets.symmetric(horizontal: 26.h), child: Text("msg_add_plant_details2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargePrimaryContainerLight.copyWith(height: 1.33))), SizedBox(height: 13.v), Align(alignment: Alignment.centerRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgArrowPrimarycontainer, height: 161.v, width: 123.h), Padding(padding: EdgeInsets.only(left: 32.h, top: 110.v, bottom: 3.v), child: CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, decoration: IconButtonStyleHelper.outlineBlack, onTap: () {onTapBtnBG(context);}, child: CustomImageView(imagePath: ImageConstant.imgBg)))])), SizedBox(height: 26.v), CustomElevatedButton(text: "lbl_continue".tr), SizedBox(height: 58.v), _buildDeleteItem(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_first_visit2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildThirtyThree(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 8.v, bottom: 6.v), child: Container(height: 4.v, width: 269.h, decoration: BoxDecoration(color: appTheme.gray60002.withOpacity(0.12), borderRadius: BorderRadius.circular(2.h)), child: ClipRRect(borderRadius: BorderRadius.circular(2.h), child: LinearProgressIndicator(value: 0.33, backgroundColor: appTheme.gray60002.withOpacity(0.12), valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary)))))), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_3_of_3".tr, style: CustomTextStyles.bodySmallBluegray900))]); } 
/// Section Widget
Widget _buildDeleteItem(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_delete_1_item".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallRed60001), SizedBox(height: 8.v), Divider(color: appTheme.gray600), SizedBox(height: 7.v), Text("lbl_cancel".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmall_1), SizedBox(height: 4.v)])); } 
/// Navigates to the ten1Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.ten1Screen, ); } 
/// Navigates to the twelveScreen when the action is triggered.
onTapBtnBG(BuildContext context) { NavigatorService.pushNamed(AppRoutes.twelveScreen, ); } 
 }
