import 'notifier/twentyseven_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';class TwentysevenScreen extends ConsumerStatefulWidget {const TwentysevenScreen({Key? key}) : super(key: key);

@override TwentysevenScreenState createState() =>  TwentysevenScreenState();

 }
class TwentysevenScreenState extends ConsumerState<TwentysevenScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 13.v), child: Column(children: [_buildThirtyThree(context), SizedBox(height: 29.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("msg_add_plant_details".tr, style: CustomTextStyles.titleMediumGray900Medium))), SizedBox(height: 24.v), _buildPlantCard1(context), SizedBox(height: 16.v), _buildPlantCard2(context), SizedBox(height: 16.v), _buildPlantCard3(context), SizedBox(height: 84.v), Align(alignment: Alignment.centerRight, child: Container(height: 48.adaptSize, width: 48.adaptSize, margin: EdgeInsets.only(right: 1.h), decoration: AppDecoration.outlineBlack9001, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgBg, height: 48.adaptSize, width: 48.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgPlus, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center)]))), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinueButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_first_visit2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildThirtyThree(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 8.v, bottom: 6.v), child: Container(height: 4.v, width: 269.h, decoration: BoxDecoration(color: appTheme.gray60002.withOpacity(0.12), borderRadius: BorderRadius.circular(2.h)), child: ClipRRect(borderRadius: BorderRadius.circular(2.h), child: LinearProgressIndicator(value: 0.33, backgroundColor: appTheme.gray60002.withOpacity(0.12), valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary)))))), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_3_of_3".tr, style: CustomTextStyles.bodySmallBluegray900))]); } 
/// Section Widget
Widget _buildPlantCard1(BuildContext context) { return GestureDetector(onTap: () {onTapPlantCard1(context);}, child: Container(margin: EdgeInsets.symmetric(horizontal: 1.h), padding: EdgeInsets.all(8.h), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 80.v, width: 92.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle96, height: 80.v, width: 92.h, radius: BorderRadius.circular(5.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(height: 80.v, width: 92.h, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(0.4), borderRadius: BorderRadius.circular(5.h))))])), Padding(padding: EdgeInsets.only(left: 11.h, top: 9.v, bottom: 9.v), child: _buildFrame(context, tagNumber: "lbl_tag_number".tr, text: "lbl".tr, twoMillionThreeHundredFortySix: "lbl_2345656".tr, variety: "lbl_variety".tr, text1: "lbl".tr, seven: "lbl_07".tr, species: "lbl_species".tr, text2: "lbl".tr, two: "lbl_02".tr)), CustomImageView(imagePath: ImageConstant.imgHugeIconArrow, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 30.h, top: 28.v, bottom: 28.v))]))); } 
/// Section Widget
Widget _buildPlantCard2(BuildContext context) { return GestureDetector(onTap: () {onTapPlantCard2(context);}, child: Container(margin: EdgeInsets.symmetric(horizontal: 1.h), padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [SizedBox(height: 80.v, width: 92.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle96, height: 80.v, width: 92.h, radius: BorderRadius.circular(5.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(height: 80.v, width: 92.h, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(0.4), borderRadius: BorderRadius.circular(5.h))))])), Padding(padding: EdgeInsets.symmetric(vertical: 9.v), child: _buildTagNumber(context, tagNumber: "lbl_tag_number".tr, text: "lbl".tr, twoMillionThreeHundredFortySix: "lbl_2347897".tr, variety: "lbl_variety".tr, text1: "lbl".tr, seven: "lbl_07".tr, species: "lbl_species".tr, text2: "lbl".tr, two: "lbl_02".tr))]))); } 
/// Section Widget
Widget _buildPlantCard3(BuildContext context) { return GestureDetector(onTap: () {onTapPlantCard3(context);}, child: Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [SizedBox(height: 80.v, width: 92.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle96, height: 80.v, width: 92.h, radius: BorderRadius.circular(5.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(height: 80.v, width: 92.h, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(0.4), borderRadius: BorderRadius.circular(5.h))))])), Padding(padding: EdgeInsets.symmetric(vertical: 9.v), child: _buildTagNumber(context, tagNumber: "lbl_tag_number".tr, text: "lbl".tr, twoMillionThreeHundredFortySix: "lbl_2346745".tr, variety: "lbl_variety".tr, text1: "lbl".tr, seven: "lbl_07".tr, species: "lbl_species".tr, text2: "lbl".tr, two: "lbl_02".tr))]))); } 
/// Section Widget
Widget _buildContinueButton(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v)); } 
/// Common widget
Widget _buildFrame(BuildContext context, {required String tagNumber, required String text, required String twoMillionThreeHundredFortySix, required String variety, required String text1, required String seven, required String species, required String text2, required String two, }) { return SizedBox(height: 60.v, width: 134.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.topCenter, child: Container(width: 134.h, margin: EdgeInsets.only(bottom: 40.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(tagNumber, style: CustomTextStyles.bodySmallGray900.copyWith(color: appTheme.gray900))), Padding(padding: EdgeInsets.only(top: 1.v), child: Text(text, style: CustomTextStyles.labelLargeGray900.copyWith(color: appTheme.gray900))), Text(twoMillionThreeHundredFortySix, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray500))]))), Align(alignment: Alignment.centerLeft, child: Container(width: 99.h, margin: EdgeInsets.only(top: 19.v, right: 35.h, bottom: 19.v), child: Row(children: [Text(variety, style: CustomTextStyles.bodySmallGray900.copyWith(color: appTheme.gray900)), Spacer(), Text(text1, style: CustomTextStyles.labelLargeGray900.copyWith(color: appTheme.gray900)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text(seven, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray500)))]))), Align(alignment: Alignment.bottomLeft, child: Container(width: 99.h, margin: EdgeInsets.only(top: 40.v, right: 35.h), child: Row(children: [Text(species, style: CustomTextStyles.bodySmallGray900.copyWith(color: appTheme.gray900)), Spacer(), Text(text2, style: CustomTextStyles.labelLargeGray900.copyWith(color: appTheme.gray900)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text(two, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray500)))])))])); } 
/// Common widget
Widget _buildTagNumber(BuildContext context, {required String tagNumber, required String text, required String twoMillionThreeHundredFortySix, required String variety, required String text1, required String seven, required String species, required String text2, required String two, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 60.v, width: 134.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.topCenter, child: Container(width: 134.h, margin: EdgeInsets.only(bottom: 40.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(tagNumber, style: CustomTextStyles.bodySmallGray900.copyWith(color: appTheme.gray900))), Padding(padding: EdgeInsets.only(top: 1.v), child: Text(text, style: CustomTextStyles.labelLargeGray900.copyWith(color: appTheme.gray900))), Text(twoMillionThreeHundredFortySix, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray500))]))), Align(alignment: Alignment.centerLeft, child: Container(width: 99.h, margin: EdgeInsets.only(top: 19.v, right: 35.h, bottom: 19.v), child: Row(children: [Text(variety, style: CustomTextStyles.bodySmallGray900.copyWith(color: appTheme.gray900)), Spacer(), Text(text1, style: CustomTextStyles.labelLargeGray900.copyWith(color: appTheme.gray900)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text(seven, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray500)))]))), Align(alignment: Alignment.bottomLeft, child: Container(width: 99.h, margin: EdgeInsets.only(top: 40.v, right: 35.h), child: Row(children: [Text(species, style: CustomTextStyles.bodySmallGray900.copyWith(color: appTheme.gray900)), Spacer(), Text(text2, style: CustomTextStyles.labelLargeGray900.copyWith(color: appTheme.gray900)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text(two, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray500)))])))])), CustomImageView(imagePath: ImageConstant.imgHugeIconArrow, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 30.h, top: 17.v, bottom: 18.v))]); } 
/// Navigates to the ten1Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.ten1Screen, ); } 
/// Navigates to the twentyeightScreen when the action is triggered.
onTapPlantCard1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.twentyeightScreen, ); } 
/// Navigates to the twentyeightScreen when the action is triggered.
onTapPlantCard2(BuildContext context) { NavigatorService.pushNamed(AppRoutes.twentyeightScreen, ); } 
/// Navigates to the twentyeightScreen when the action is triggered.
onTapPlantCard3(BuildContext context) { NavigatorService.pushNamed(AppRoutes.twentyeightScreen, ); } 
 }
