import '../k118_screen/widgets/userprofilelist1_item_widget.dart';import 'models/userprofilelist1_item_model.dart';import 'notifier/k118_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/widgets/custom_icon_button.dart';import 'package:tissue_culture/widgets/custom_text_form_field.dart';import 'package:tissue_culture/presentation/k119_bottomsheet/k119_bottomsheet.dart';class K118Screen extends ConsumerStatefulWidget {const K118Screen({Key? key}) : super(key: key);

@override K118ScreenState createState() =>  K118ScreenState();

 }
class K118ScreenState extends ConsumerState<K118Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 20.v), Text("lbl_detail_summary".tr, style: CustomTextStyles.titleMediumPlusJakartaSansGray900), SizedBox(height: 22.v), _buildSuckerCollectionFrame(context, suckercollectiondetails: "lbl_yield_details".tr), SizedBox(height: 8.v), Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(k118Notifier).participantsController, hintText: "msg_actual_weight_of".tr, textInputAction: TextInputAction.done, maxLines: 3, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 11.v));}), SizedBox(height: 22.v), _buildSuckerCollectionFrame(context, suckercollectiondetails: "msg_sucker_collection".tr), SizedBox(height: 16.v), _buildUserProfileList(context), SizedBox(height: 12.v), _buildTotalSuckerCollectedRow(context), SizedBox(height: 25.v), Text("lbl_rejected_plant".tr, style: CustomTextStyles.titleMediumGray900Medium), SizedBox(height: 14.v), Container(height: 1.v, width: 312.h, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1))), _buildRejectedStack(context), SizedBox(height: 11.v), CustomElevatedButton(text: "lbl_continue".tr, onPressed: () {onTapContinue(context);})])), bottomNavigationBar: _buildFrameRow(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "msg_collection_visit2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildUserProfileList(BuildContext context) { return Consumer(builder: (context, ref, _) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 8.0.v), child: SizedBox(width: 312.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.blueGray100)));}, itemCount: ref.watch(k118Notifier).k118ModelObj?.userprofilelist1ItemList.length ?? 0, itemBuilder: (context, index) {Userprofilelist1ItemModel model = ref.watch(k118Notifier).k118ModelObj?.userprofilelist1ItemList[index] ?? Userprofilelist1ItemModel(); return Userprofilelist1ItemWidget(model);});}); } 
/// Section Widget
Widget _buildTotalSuckerCollectedRow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_total_sucker_collected".tr, style: CustomTextStyles.labelLargeInterGray90003), Text("lbl_40".tr, style: CustomTextStyles.labelLargeInterGray700)]); } 
/// Section Widget
Widget _buildRejectedStack(BuildContext context) { return SizedBox(height: 16.v, width: 312.h, child: Stack(alignment: Alignment.centerRight, children: [Align(alignment: Alignment.center, child: Container(height: 16.v, width: 312.h, decoration: BoxDecoration(color: appTheme.deepOrange50, borderRadius: BorderRadius.vertical(top: Radius.circular(12.h))))), Align(alignment: Alignment.centerRight, child: Container(width: 56.h, margin: EdgeInsets.only(right: 14.h), padding: EdgeInsets.symmetric(horizontal: 8.h), decoration: AppDecoration.fillDeepOrange.copyWith(borderRadius: BorderRadiusStyle.circleBorder8), child: Text("lbl_rejected".tr, style: CustomTextStyles.labelMediumRed600)))])); } 
/// Section Widget
Widget _buildFrameRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 32.h, right: 38.h, bottom: 3.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 92.adaptSize, width: 92.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle96, height: 92.adaptSize, width: 92.adaptSize, radius: BorderRadius.circular(5.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(height: 92.adaptSize, width: 92.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(0.4), borderRadius: BorderRadius.circular(5.h))))])), Padding(padding: EdgeInsets.only(left: 12.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_tag_number".tr, style: CustomTextStyles.bodySmallGray900), Text("lbl".tr, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeGray900), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_2347897".tr, textAlign: TextAlign.center, style: theme.textTheme.labelLarge))]), Padding(padding: EdgeInsets.only(top: 48.v), child: _buildSpeciesRow(context, speciesText: "lbl_variety".tr, colonText: "lbl".tr, numberText: "lbl_07".tr)), Padding(padding: EdgeInsets.only(top: 68.v), child: _buildSpeciesRow(context, speciesText: "lbl_species".tr, colonText: "lbl".tr, numberText: "lbl_02".tr)), Container(width: 186.h, margin: EdgeInsets.only(top: 96.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 24.v, width: 87.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 24.v, width: 87.h, decoration: BoxDecoration(color: appTheme.gray200, borderRadius: BorderRadius.circular(4.h)))), Align(alignment: Alignment.center, child: Text("lbl_reject".tr, style: CustomTextStyles.labelMediumGray600))])), SizedBox(height: 24.v, width: 87.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 24.v, width: 87.h, decoration: BoxDecoration(color: appTheme.blueGray50, borderRadius: BorderRadius.circular(4.h)))), Align(alignment: Alignment.center, child: Text("lbl_view_details".tr, style: theme.textTheme.labelMedium))]))]))]))])); } 
/// Common widget
Widget _buildSuckerCollectionFrame(BuildContext context, {required String suckercollectiondetails, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(suckercollectiondetails, style: CustomTextStyles.titleMediumGray900Medium.copyWith(color: appTheme.gray900)), Padding(padding: EdgeInsets.only(top: 3.v), child: CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgFill)))]); } 
/// Common widget
Widget _buildSpeciesRow(BuildContext context, {required String speciesText, required String colonText, required String numberText, }) { return Row(children: [Text(speciesText, style: CustomTextStyles.bodySmallGray900.copyWith(color: appTheme.gray900)), Text(colonText, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeGray900.copyWith(color: appTheme.gray900)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text(numberText, textAlign: TextAlign.center, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray500)))]); } 
/// Navigates to the k116Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k116Screen, ); } 

/// Shows a modal bottom sheet with [K119Bottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapContinue(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>K119Bottomsheet(),isScrollControlled: true); } 
 }
