import 'models/twenty_model.dart';import 'notifier/twenty_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/core/utils/validation_functions.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_drop_down.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/widgets/custom_text_form_field.dart';class TwentyScreen extends ConsumerStatefulWidget {const TwentyScreen({Key? key}) : super(key: key);

@override TwentyScreenState createState() =>  TwentyScreenState();

 }

// ignore_for_file: must_be_immutable
class TwentyScreenState extends ConsumerState<TwentyScreen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: SingleChildScrollView(padding: EdgeInsets.only(top: 13.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildFortyOne(context), SizedBox(height: 23.v), Text("msg_add_plant_details".tr, style: CustomTextStyles.titleMediumGray900Medium), SizedBox(height: 16.v), _buildTitle(context), SizedBox(height: 16.v), _buildDate(context), SizedBox(height: 16.v), _buildTitle1(context), SizedBox(height: 22.v), Text("lbl_disease".tr, style: CustomTextStyles.titleMediumGray900Medium), SizedBox(height: 16.v), _buildName(context), SizedBox(height: 16.v), _buildTitle2(context), SizedBox(height: 24.v), Text("lbl_plant_variety".tr, style: CustomTextStyles.titleMediumGray900Medium), SizedBox(height: 14.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_plant".tr, items: ref.watch(twentyNotifier).twentyModelObj?.dropdownItemList ?? [], onChanged: (value) {ref.watch(twentyNotifier).selectedDropDownValue = value;});}), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(hintText: "msg_select_the_plant2".tr, items: ref.watch(twentyNotifier).twentyModelObj?.dropdownItemList1 ?? [], contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 7.v), borderDecoration: DropDownStyleHelper.fillOnErrorContainerTL2, onChanged: (value) {ref.watch(twentyNotifier).selectedDropDownValue1 = value;});}), SizedBox(height: 15.v), _buildContinue(context), SizedBox(height: 58.v), _buildDeleteItem(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_plant_detail".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildFortyOne(BuildContext context) { return Row(children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 8.v, bottom: 6.v), child: Container(height: 4.v, width: 269.h, decoration: BoxDecoration(color: appTheme.gray60002.withOpacity(0.12), borderRadius: BorderRadius.circular(2.h)), child: ClipRRect(borderRadius: BorderRadius.circular(2.h), child: LinearProgressIndicator(value: 0.25, backgroundColor: appTheme.gray60002.withOpacity(0.12), valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary)))))), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_1_of_4".tr, style: CustomTextStyles.bodySmallBluegray900))]); } 
/// Section Widget
Widget _buildTitle(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(twentyNotifier).titleController, hintText: "msg_enter_the_plant".tr);}); } 
/// Section Widget
Widget _buildDate(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_expected_date_of".tr, style: theme.textTheme.bodyMedium), CustomImageView(imagePath: ImageConstant.imgGroup1000001977, height: 20.adaptSize, width: 20.adaptSize)])); } 
/// Section Widget
Widget _buildTitle1(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(twentyNotifier).titleController1, hintText: "msg_enter_the_tag_number".tr, textInputType: TextInputType.number, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;});}); } 
/// Section Widget
Widget _buildName(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(twentyNotifier).nameController, hintText: "msg_enter_the_name_of".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}); } 
/// Section Widget
Widget _buildTitle2(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(twentyNotifier).titleController2, hintText: "msg_enter_the_details".tr, textInputAction: TextInputAction.done);}); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, onPressed: () {onTapContinue(context);}); } 
/// Section Widget
Widget _buildDeleteItem(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_delete_1_item".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallRed60001), SizedBox(height: 8.v), Divider(color: appTheme.gray600), SizedBox(height: 7.v), Text("lbl_cancel".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmall_1), SizedBox(height: 4.v)])); } 
/// Navigates to the nineteenScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.nineteenScreen, ); } 
/// Navigates to the twentyoneScreen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.twentyoneScreen, ); } 
 }
