import 'notifier/visitschange_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/widgets/custom_text_form_field.dart';class VisitschangeScreen extends ConsumerStatefulWidget {const VisitschangeScreen({Key? key}) : super(key: key);

@override VisitschangeScreenState createState() =>  VisitschangeScreenState();

 }
class VisitschangeScreenState extends ConsumerState<VisitschangeScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 714.v), child: Container(decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.outlineBlack900.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 4.v, width: 40.h, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgClose, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 74.h), child: Text("lbl_cancel_visit".tr, textAlign: TextAlign.center, style: theme.textTheme.titleLarge))])), SizedBox(height: 32.v), Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(visitschangeNotifier).titleController, hintText: "msg_enter_the_reason2".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 38.v));}), SizedBox(height: 218.v), CustomElevatedButton(text: "lbl_update".tr), SizedBox(height: 8.v)]))))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), title: Container(height: 24.v, width: 43.h, margin: EdgeInsets.only(left: 28.h), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(right: 42.h), child: SizedBox(height: 24.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: theme.colorScheme.primary)))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_search".tr, style: CustomTextStyles.titleSmallGray600)))])), styleType: Style.bgFill_3); } 
/// Navigates to the visitschangeThreeScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.visitschangeThreeScreen, ); } 
 }
