import 'notifier/onboarding_three_notifier.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';class OnboardingThreeScreen extends ConsumerStatefulWidget {const OnboardingThreeScreen({Key? key}) : super(key: key);

@override OnboardingThreeScreenState createState() =>  OnboardingThreeScreenState();

 }
class OnboardingThreeScreenState extends ConsumerState<OnboardingThreeScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onErrorContainer.withOpacity(1), appBar: _buildAppBar(context), body: Container(width: 312.h, margin: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 5.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_heading".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 10.v), SizedBox(width: 312.h, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_lorem_ipsum_is_simply2".tr, style: CustomTextStyles.titleSmallff1e1f20), TextSpan(text: "msg_lorem_ipsum_is_simply3".tr, style: CustomTextStyles.titleSmallff1e1f20)]), textAlign: TextAlign.left)), SizedBox(height: 104.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 8.v, margin: EdgeInsets.only(top: 21.v, bottom: 19.v), child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 8, activeDotColor: theme.colorScheme.primaryContainer.withOpacity(1), dotColor: appTheme.gray300, dotHeight: 8.v, dotWidth: 8.h))), CustomElevatedButton(width: 200.h, text: "lbl_get_started".tr, buttonStyle: CustomButtonStyles.fillPrimary, onPressed: () {onTapGetStarted(context);})])])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 440.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.fromLTRB(20.h, 12.v, 316.h, 404.v), onTap: () {onTapArrowDown(context);}), styleType: Style.bgFill); } 
/// Navigates to the onboardingTwoScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.onboardingTwoScreen, ); } 
/// Navigates to the loginScreen when the action is triggered.
onTapGetStarted(BuildContext context) { NavigatorService.pushNamed(AppRoutes.loginScreen, ); } 
 }
