import '../home_screen/widgets/selectyourappcard_item_widget.dart';import 'models/selectyourappcard_item_model.dart';import 'notifier/home_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_eight.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_four.dart';import 'package:tissue_culture/widgets/app_bar/appbar_trailing_image.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';class HomeScreen extends ConsumerStatefulWidget {const HomeScreen({Key? key}) : super(key: key);

@override HomeScreenState createState() =>  HomeScreenState();

 }
class HomeScreenState extends ConsumerState<HomeScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 13.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_select_your_app".tr, style: CustomTextStyles.titleLargeGray900)), SizedBox(height: 10.v), _buildSelectYourAppCard(context), SizedBox(height: 20.v), _buildFrameEighteen(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 67.v, leadingWidth: 64.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgRectangle14, margin: EdgeInsets.only(left: 24.h, top: 6.v, bottom: 9.v)), title: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(children: [AppbarSubtitleFour(text: "lbl_rajan_nair".tr, margin: EdgeInsets.only(right: 18.h)), AppbarSubtitleEight(text: "lbl_lab_technician".tr)])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgHugeIconInter, margin: EdgeInsets.fromLTRB(24.h, 14.v, 24.h, 17.v))]); } 
/// Section Widget
Widget _buildSelectYourAppCard(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Consumer(builder: (context, ref, _) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 101.v, crossAxisCount: 2, mainAxisSpacing: 32.h, crossAxisSpacing: 32.h), physics: NeverScrollableScrollPhysics(), itemCount: ref.watch(homeNotifier).homeModelObj?.selectyourappcardItemList.length ?? 0, itemBuilder: (context, index) {SelectyourappcardItemModel model = ref.watch(homeNotifier).homeModelObj?.selectyourappcardItemList[index] ?? SelectyourappcardItemModel(); return SelectyourappcardItemWidget(model, onTapCard: () {onTapCard(context);});});})); } 
/// Section Widget
Widget _buildFrameEighteen(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_work_log_today".tr, style: CustomTextStyles.titleLargeGray900), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 7.v), child: Text("lbl_view_all".tr, style: CustomTextStyles.bodyMediumGray600))]); } 
/// Navigates to the k146Screen when the action is triggered.
onTapCard(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k146Screen, ); } 
 }
