import 'notifier/k131_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/presentation/k132_dialog/k132_dialog.dart';class K131Screen extends ConsumerStatefulWidget {const K131Screen({Key? key}) : super(key: key);

@override K131ScreenState createState() =>  K131ScreenState();

 }
class K131ScreenState extends ConsumerState<K131Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 15.v), child: Column(children: [Text("msg_scan_a_parent_qr".tr, style: theme.textTheme.bodySmall), SizedBox(height: 20.v), _buildScanAParentQR(context), SizedBox(height: 29.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgHugeIconInterBlueGray90004, height: 24.adaptSize, width: 24.adaptSize), CustomImageView(imagePath: ImageConstant.imgHugeIconDevic, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 20.h))]), SizedBox(height: 108.v), CustomElevatedButton(text: "lbl_allow".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), onPressed: () {onTapAllow(context);}), SizedBox(height: 68.v), _buildAllowThisAppTo(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_explant_label".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildScanAParentQR(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 42.h, vertical: 158.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_camera_permission".tr, style: CustomTextStyles.titleLargeGray50), SizedBox(height: 5.v), Text("msg_please_allow_camera".tr, style: CustomTextStyles.bodyMediumGray50), SizedBox(height: 3.v)])); } 
/// Section Widget
Widget _buildAllowThisAppTo(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [Text("msg_allow_this_app_to".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallExtraBold_1), SizedBox(height: 8.v), Divider(color: appTheme.gray600.withOpacity(0.2)), SizedBox(height: 7.v), Text("msg_while_using_this".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallPrimary), SizedBox(height: 8.v), Divider(color: appTheme.gray600.withOpacity(0.2)), SizedBox(height: 7.v), Text("lbl_only_this_time".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallPrimary), SizedBox(height: 8.v), Divider(color: appTheme.gray600.withOpacity(0.2)), SizedBox(height: 7.v), Text("lbl_don_t_allow".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallPrimary)])); } 
/// Navigates to the k130Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k130Screen, ); } 

/// Displays a dialog with the [K132Dialog] content.
onTapAllow(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: K132Dialog(),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
