import 'notifier/twentytwo_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';class TwentytwoScreen extends ConsumerStatefulWidget {const TwentytwoScreen({Key? key}) : super(key: key);

@override TwentytwoScreenState createState() =>  TwentytwoScreenState();

 }
class TwentytwoScreenState extends ConsumerState<TwentytwoScreen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 13.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildFortyThree(context), SizedBox(height: 23.v), Text("msg_upload_the_image2".tr, style: CustomTextStyles.titleMediumGray900Medium), SizedBox(height: 22.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 22.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 20.v), CustomElevatedButton(text: "msg_open_camera_take".tr, leftIcon: Container(margin: EdgeInsets.only(right: 13.h), child: CustomImageView(imagePath: ImageConstant.imgCamera, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL24, buttonTextStyle: CustomTextStyles.labelLargeOnErrorContainer, onPressed: () {onTapOpenCameraTakePhoto(context);}), SizedBox(height: 318.v), _buildDeleteItem(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_plant_detail".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildFortyThree(BuildContext context) { return Row(children: [Container(height: 4.v, width: 269.h, margin: EdgeInsets.symmetric(vertical: 7.v), child: Stack(alignment: Alignment.centerRight, children: [Align(alignment: Alignment.center, child: SizedBox(width: 269.h, child: Divider(color: appTheme.gray60002.withOpacity(0.12)))), Align(alignment: Alignment.centerRight, child: SizedBox(width: 135.h, child: Divider(color: theme.colorScheme.primary, endIndent: 67.h)))])), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_3_of_4".tr, style: CustomTextStyles.bodySmallBluegray900))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 125.h, vertical: 56.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgUser, height: 20.adaptSize, width: 20.adaptSize), SizedBox(height: 6.v), Text("lbl_select_file".tr, style: CustomTextStyles.labelLargeGray50001)])); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 11.v, bottom: 12.v), child: SizedBox(width: 138.h, child: Divider())), Text("lbl_or".tr, style: CustomTextStyles.bodyLargeGray90002), Padding(padding: EdgeInsets.only(top: 11.v, bottom: 12.v), child: SizedBox(width: 138.h, child: Divider()))]); } 
/// Section Widget
Widget _buildDeleteItem(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_delete_1_item".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallRed60001), SizedBox(height: 8.v), Divider(color: appTheme.gray600), SizedBox(height: 7.v), Text("lbl_cancel".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmall_1), SizedBox(height: 4.v)])); } 
/// Navigates to the twentyScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.twentyScreen, ); } 
/// Navigates to the twentythreeScreen when the action is triggered.
onTapOpenCameraTakePhoto(BuildContext context) { NavigatorService.pushNamed(AppRoutes.twentythreeScreen, ); } 
 }
