import 'notifier/k45_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_search_view.dart';class K45Page extends ConsumerStatefulWidget {const K45Page({Key? key}) : super(key: key);

@override K45PageState createState() =>  K45PageState();

 }
class K45PageState extends ConsumerState<K45Page> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [Consumer(builder: (context, ref, _) {return CustomSearchView(controller: ref.watch(k45Notifier).searchController, hintText: "lbl_search".tr);}), Spacer(), CustomImageView(imagePath: ImageConstant.imgCurrencyCrushOnline, height: 133.v, width: 155.h), SizedBox(height: 22.v), SizedBox(width: 209.h, child: Text("msg_add_a_visit_details".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargeGray600.copyWith(height: 1.33))), SizedBox(height: 30.v), Align(alignment: Alignment.centerRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrow, height: 129.v, width: 99.h, margin: EdgeInsets.only(bottom: 25.v)), Container(height: 48.adaptSize, width: 48.adaptSize, margin: EdgeInsets.only(left: 44.h, top: 107.v), decoration: AppDecoration.outlineBlack9001, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgBg, height: 48.adaptSize, width: 48.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgPlus, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.center)]))])), SizedBox(height: 8.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_manage_visits2".tr), styleType: Style.bgFill_2); } 
/// Navigates to the mainHomescreenScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.mainHomescreenScreen, ); } 
 }
