import 'notifier/k61_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/widgets/custom_pin_code_text_field.dart';import 'package:tissue_culture/presentation/k62_dialog/k62_dialog.dart';class K61Screen extends ConsumerStatefulWidget {const K61Screen({Key? key}) : super(key: key);

@override K61ScreenState createState() =>  K61ScreenState();

 }
class K61ScreenState extends ConsumerState<K61Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 13.v), child: Column(children: [_buildTwentyThree(context), SizedBox(height: 23.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_upload_the_image".tr, style: CustomTextStyles.titleMediumGray900Medium))), SizedBox(height: 23.v), _buildWidget(context), SizedBox(height: 11.v), _buildOtpView(context), SizedBox(height: 21.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgHugeIconInterPrimarycontainer, height: 24.adaptSize, width: 24.adaptSize), CustomImageView(imagePath: ImageConstant.imgGroup1000002037, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 32.h))]), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinue(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_first_visit2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildTwentyThree(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 4.v, width: 269.h, margin: EdgeInsets.symmetric(vertical: 7.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 269.h, child: Divider(color: appTheme.gray60002.withOpacity(0.12)))), Align(alignment: Alignment.center, child: SizedBox(width: 90.h, child: Divider(color: theme.colorScheme.primary)))])), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_2_of_3".tr, style: CustomTextStyles.bodySmallBluegray900))])); } 
/// Section Widget
Widget _buildWidget(BuildContext context) { return SizedBox(height: 312.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle88, height: 312.v, width: 360.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillBlack, child: CustomImageView(imagePath: ImageConstant.imgGroup1000002042, height: 20.adaptSize, width: 20.adaptSize, onTap: () {onTapImgImage(context);})))])); } 
/// Section Widget
Widget _buildOtpView(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, color: theme.colorScheme.primaryContainer.withOpacity(0.08), shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder12), child: Container(height: 56.v, width: 312.h, padding: EdgeInsets.all(8.h), decoration: AppDecoration.fillPrimaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Stack(alignment: Alignment.centerRight, children: [Consumer(builder: (context, ref, _) {return CustomPinCodeTextField(context: context, controller: ref.watch(k61Notifier).otpController, onChanged: (value) {ref.watch(k61Notifier).otpController?.text = value;});}), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 15.h), child: Text("lbl_8".tr, style: CustomTextStyles.labelLargeOnErrorContainer_1)))]))); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapContinue(context);}); } 
/// Navigates to the k58Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k58Screen, ); } 

/// Displays a dialog with the [K62Dialog] content.
onTapImgImage(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: K62Dialog(),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
/// Navigates to the elevenScreen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.elevenScreen, ); } 
 }
