import 'notifier/k138_notifier.dart';import 'package:flutter/material.dart';import 'package:qr_flutter/qr_flutter.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';class K138Screen extends ConsumerStatefulWidget {const K138Screen({Key? key}) : super(key: key);

@override K138ScreenState createState() =>  K138ScreenState();

 }
class K138ScreenState extends ConsumerState<K138Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 24.h, top: 120.v, right: 24.h), child: Column(children: [_buildExplantLabel(context), SizedBox(height: 40.v), Container(margin: EdgeInsets.symmetric(horizontal: 82.h), padding: EdgeInsets.symmetric(horizontal: 58.h, vertical: 11.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPrint, height: 32.adaptSize, width: 32.adaptSize), SizedBox(height: 2.v), Text("lbl_print".tr, style: CustomTextStyles.bodyMediumBlack900)])), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBackToHome(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_explant_label".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildExplantLabel(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: theme.colorScheme.onErrorContainer.withOpacity(1), shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder12), child: Container(height: 149.v, width: 312.h, padding: EdgeInsets.symmetric(horizontal: 40.h, vertical: 6.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 32.v), child: QrImageView(data: 'https://www.google.com', size: 93.adaptSize)), Padding(padding: EdgeInsets.only(left: 23.h, top: 45.v, bottom: 15.v), child: Column(children: [SizedBox(width: 116.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_888".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Text("lbl_080622".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)])), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_08".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold))])]))])), Align(alignment: Alignment.topCenter, child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Text("lbl_07".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold), Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_01".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_da".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)), Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_080808".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold)), Padding(padding: EdgeInsets.only(left: 17.h), child: Text("lbl_2".tr, style: CustomTextStyles.titleLargePrimaryContainerExtraBold))]))]))); } 
/// Section Widget
Widget _buildBackToHome(BuildContext context) { return CustomElevatedButton(text: "lbl_back_to_home".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapBackToHome(context);}); } 
/// Navigates to the k137Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k137Screen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapBackToHome(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
 }
