import 'models/k54_model.dart';import 'notifier/k54_notifier.dart';import 'package:flutter/material.dart';import 'package:tissue_culture/core/app_export.dart';import 'package:tissue_culture/widgets/app_bar/appbar_leading_image.dart';import 'package:tissue_culture/widgets/app_bar/appbar_subtitle_one.dart';import 'package:tissue_culture/widgets/app_bar/custom_app_bar.dart';import 'package:tissue_culture/widgets/custom_checkbox_button.dart';import 'package:tissue_culture/widgets/custom_drop_down.dart';import 'package:tissue_culture/widgets/custom_elevated_button.dart';import 'package:tissue_culture/widgets/custom_text_form_field.dart';import 'package:tissue_culture/presentation/k56_dialog/k56_dialog.dart';class K54Screen extends ConsumerStatefulWidget {const K54Screen({Key? key}) : super(key: key);

@override K54ScreenState createState() =>  K54ScreenState();

 }
class K54ScreenState extends ConsumerState<K54Screen> {@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 13.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildThirteen(context), SizedBox(height: 21.v), Text("msg_enter_the_field".tr, style: CustomTextStyles.titleMediumGray900Medium), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_field".tr, items: ref.watch(k54Notifier).k54ModelObj?.dropdownItemList ?? [], onChanged: (value) {ref.watch(k54Notifier).selectedDropDownValue = value;});}), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_soil".tr, items: ref.watch(k54Notifier).k54ModelObj?.dropdownItemList1 ?? [], onChanged: (value) {ref.watch(k54Notifier).selectedDropDownValue1 = value;});}), SizedBox(height: 16.v), _buildDate(context), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_watering".tr, items: ref.watch(k54Notifier).k54ModelObj?.dropdownItemList2 ?? [], onChanged: (value) {ref.watch(k54Notifier).selectedDropDownValue2 = value;});}), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 16.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownGray900, height: 20.adaptSize, width: 20.adaptSize)), hintText: "msg_select_the_field2".tr, items: ref.watch(k54Notifier).k54ModelObj?.dropdownItemList3 ?? [], onChanged: (value) {ref.watch(k54Notifier).selectedDropDownValue3 = value;});}), SizedBox(height: 16.v), Consumer(builder: (context, ref, _) {return CustomTextFormField(controller: ref.watch(k54Notifier).titleController, hintText: "msg_enter_no_of_plants".tr, textInputAction: TextInputAction.done);}), SizedBox(height: 24.v), _buildPestHistory(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinue(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_first_visit2".tr), styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildThirteen(BuildContext context) { return Row(children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 8.v, bottom: 6.v), child: Container(height: 4.v, width: 269.h, decoration: BoxDecoration(color: appTheme.gray60002.withOpacity(0.12), borderRadius: BorderRadius.circular(2.h)), child: ClipRRect(borderRadius: BorderRadius.circular(2.h), child: LinearProgressIndicator(value: 0.33, backgroundColor: appTheme.gray60002.withOpacity(0.12), valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary)))))), Padding(padding: EdgeInsets.only(left: 11.h), child: Text("lbl_1_of_3".tr, style: CustomTextStyles.bodySmallBluegray900))]); } 
/// Section Widget
Widget _buildDate(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_select_date_of_planting".tr, style: theme.textTheme.bodyMedium), CustomImageView(imagePath: ImageConstant.imgGroup1000001977, height: 20.adaptSize, width: 20.adaptSize, onTap: () {onTapImgImage(context);})])); } 
/// Section Widget
Widget _buildPestHistory(BuildContext context) { return Consumer(builder: (context, ref, _) {return CustomCheckboxButton(width: 312.h, text: "lbl_pest_history".tr, value: ref.watch(k54Notifier).pestHistory, textStyle: CustomTextStyles.titleMediumBlack900, isRightCheck: true, onChange: (value) {ref.read(k54Notifier.notifier).changeCheckBox1(value);});}); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapContinue(context);}); } 
/// Navigates to the k48Screen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k48Screen, ); } 

/// Displays a dialog with the [K56Dialog] content.
onTapImgImage(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: K56Dialog(),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
/// Navigates to the k58Screen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.k58Screen, ); } 
 }
